# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNP_TW16' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SNP_TW16
  pod 'Pastel'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'ObjectMapper', '~> 3.4'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'FLEX', :configurations => ['Debug']
  pod 'MultiDegreeLikeButton'
  pod 'KMPlaceholderTextView'
  pod 'SDWebImage', '~> 5.0'
end
